# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='别名'),
            preserve_default=False,
        ),
    ]
