# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='可访问的地址')),
                ('url_name', models.CharField(max_length=32, verbose_name='地址标题')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='职位名称')),
                ('Permission', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='职位权限')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户账号')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='账号的职位')),
            ],
        ),
    ]
