# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Permission',
            new_name='permission',
        ),
    ]
